# used by local ft to make requests to wiremock
spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:9000/realms/shopping-api

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka